// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-generated MLB betting picks flow.
 *
 * - generateAiPicks - A function that generates AI-driven MLB betting picks.
 * - GenerateAiPicksInput - The input type for the generateAiPicks function.
 * - GenerateAiPicksOutput - The return type for the generateAiPicks function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAiPicksInputSchema = z.object({
  teamData: z.string().describe('Comprehensive data for all MLB teams.'),
  weatherAnalysis: z.string().describe('Weather analysis for game locations.'),
  injuryAnalysis: z.string().describe('Injury reports for key players.'),
  parkFactorAnalysis: z.string().describe('Park factor analysis for each stadium.'),
  liveOdds: z.string().describe('Real-time betting odds from various sources.'),
});
export type GenerateAiPicksInput = z.infer<typeof GenerateAiPicksInputSchema>;

const AiPickSchema = z.object({
  gameId: z.string().describe('The unique identifier for the MLB game.'),
  team: z.string().describe('The team the AI is recommending to bet on.'),
  pickType: z.string().describe('The type of bet (e.g., moneyline, spread, over/under).'),
  confidenceLevel: z.number().describe('The AI’s confidence level in the pick (0-100).'),
  reasoning: z.string().describe('The AI’s reasoning behind the pick.'),
});

const GenerateAiPicksOutputSchema = z.array(AiPickSchema).describe('An array of AI-generated MLB betting picks.');
export type GenerateAiPicksOutput = z.infer<typeof GenerateAiPicksOutputSchema>;

export async function generateAiPicks(input: GenerateAiPicksInput): Promise<GenerateAiPicksOutput> {
  return generateAiPicksFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateAiPicksPrompt',
  input: {schema: GenerateAiPicksInputSchema},
  output: {schema: GenerateAiPicksOutputSchema},
  prompt: `You are an AI expert specializing in generating MLB betting picks. Analyze the provided data and provide informed recommendations.

  Data Points:
  Team Data: {{{teamData}}}
  Weather Analysis: {{{weatherAnalysis}}}
  Injury Analysis: {{{injuryAnalysis}}}
  Park Factor Analysis: {{{parkFactorAnalysis}}}
  Live Odds: {{{liveOdds}}}

  Provide a list of AI-generated MLB betting picks with associated confidence levels and reasoning. The output should be an array of JSON objects, each containing the following fields:
  - gameId: The unique identifier for the MLB game.
  - team: The team the AI is recommending to bet on.
  - pickType: The type of bet (e.g., moneyline, spread, over/under).
  - confidenceLevel: The confidence level of the pick (0-100).
  - reasoning: The AI’s reasoning behind the pick.
  Ensure that the confidenceLevel is between 0 and 100.
  Example Output:
  [
    {
      "gameId": "12345",
      "team": "Yankees",
      "pickType": "moneyline",
      "confidenceLevel": 75,
      "reasoning": "The Yankees are playing at home and have a strong pitching matchup."
    }
  ]
  `,
});

const generateAiPicksFlow = ai.defineFlow(
  {
    name: 'generateAiPicksFlow',
    inputSchema: GenerateAiPicksInputSchema,
    outputSchema: GenerateAiPicksOutputSchema,
  },
  async (input) => {
    const {output} = await prompt(input);
    return output || [];
  }
);
